<?php
/**
 * SK ITC ORM Bundle Console Application
 *
 * @author Slavomir Kuzma <slavomir.kuzma@gmail.com>
 */
namespace SK\ITC\PivotalTrackerBundle\Application;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\HttpKernel\KernelInterface;

class Console extends Application
{

	/**
	 * Generated By
	 *
	 * @link http://patorjk.com/software/taag/#p=display&h=1&f=Slant&t=ITC%20Pivoval%20Tracker
	 * @var string
	 */
	private static $logo = "
    ____ ______ ______   ____   _                             __   ______                    __
   /  _//_  __// ____/  / __ \ (_)_   __ ____  _   __ ____ _ / /  /_  __/_____ ____ _ _____ / /__ ___   _____
   / /   / /  / /      / /_/ // /| | / // __ \| | / // __ `// /    / /  / ___// __ `// ___// //_// _ \ / ___/
 _/ /   / /  / /___   / ____// / | |/ // /_/ /| |/ // /_/ // /    / /  / /   / /_/ // /__ / ,<  /  __// /
/___/  /_/   \____/  /_/    /_/  |___/ \____/ |___/ \__,_//_/    /_/  /_/    \__,_/ \___//_/|_| \___//_/
                                                                                                            ";

	/**
	 *
	 * {@inheritDoc}
	 *
	 * @see \Symfony\Component\Console\Application::__construct()
	 */
	public function __construct( KernelInterface $kernel, $name = 'ITCloud Pivotal Tracker Console', $version = '${project.version}' )
	{
		parent::__construct( $kernel );

		$this->setName( $name );
		$this->setVersion( $version );
	}

	/**
	 *
	 * {@inheritDoc}
	 * @see \Symfony\Component\Console\Application::getHelp()
	 */
	public function getHelp()
	{
		return self::$logo . parent::getHelp();
	}
}